# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# License:    MIT
# References:
#   https://github.com/jwilm/alacritty



window:
        dimensions:
                columns: 80
                lines: 24


        padding:
                x: 10
                y: 10

        dynamic_padding: true

        decorations: none
font:

        size: 12.0

        normal:
                family: Code New Roman Nerd Font
                style: Regular

        bold:
                family: Code New Roman Nerd Font
                style: Bold

        italic:
                family: Code New Roman Nerd Font
                style: Italic



# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xabb2bf'

  # Cursor colors
  cursor:
    background: '0xabb2bf'
    foreground: '0x282c34'

  # Normal colors
  normal:
    black:   '0x282c34'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xe5c07b'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  # Bright colors
  bright:
    black:   '0x3e4452'
    red:     '0xbe5046'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x5c6370'


    background_opacity: 1
